// ContractShield — Legal / Terms of Service / Privacy Policy Screen
import React, { useState } from 'react';
import {
  View, Text, TouchableOpacity, ScrollView, StyleSheet,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { COLORS, SPACING, RADIUS, FONTS, SHADOWS } from '../../theme';

interface Props {
  navigation: { navigate: (name: string, params?: any) => void; goBack: () => void };
  route?: { params?: { section?: 'tos' | 'privacy' } };
}

type Tab = 'tos' | 'privacy';

const LAST_UPDATED = 'February 16, 2026';

export default function LegalScreen({ navigation, route }: Props) {
  const [tab, setTab] = useState<Tab>(route?.params?.section || 'tos');

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Text style={styles.backBtn}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Legal</Text>
      </View>

      {/* Tab toggle */}
      <View style={styles.tabRow}>
        <TouchableOpacity
          style={[styles.tabBtn, tab === 'tos' && styles.tabBtnActive]}
          onPress={() => setTab('tos')}
          activeOpacity={0.7}
        >
          <Text style={[styles.tabBtnText, tab === 'tos' && styles.tabBtnTextActive]}>Terms of Service</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.tabBtn, tab === 'privacy' && styles.tabBtnActive]}
          onPress={() => setTab('privacy')}
          activeOpacity={0.7}
        >
          <Text style={[styles.tabBtnText, tab === 'privacy' && styles.tabBtnTextActive]}>Privacy Policy</Text>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.container} contentContainerStyle={styles.content}>
        {tab === 'tos' && (
          <>
            <Text style={styles.updated}>Last updated: {LAST_UPDATED}</Text>

            <Text style={styles.sectionTitle}>1. Acceptance of Terms</Text>
            <Text style={styles.body}>
              By downloading, installing, or using ContractShield ("the App"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the App.
            </Text>

            <Text style={styles.sectionTitle}>2. Nature of Service — NOT Legal Advice</Text>
            <View style={styles.importantBox}>
              <Text style={styles.importantText}>
                ContractShield is an AI-powered informational and educational tool. The App does NOT provide legal advice, legal representation, or legal services of any kind. ContractShield is NOT a law firm and is NOT a substitute for the advice of a qualified attorney.
              </Text>
            </View>
            <Text style={styles.body}>
              The analysis, risk assessments, summaries, and suggestions provided by the App are generated by artificial intelligence and are intended for general informational purposes only. They should not be relied upon as legal advice or as the sole basis for any legal decision, including whether to sign, modify, or reject a contract.
            </Text>
            <Text style={styles.body}>
              You should always consult with a qualified, licensed attorney in your jurisdiction before signing any contract or making legal decisions. No attorney-client relationship is created by your use of the App.
            </Text>

            <Text style={styles.sectionTitle}>3. AI-Generated Content Disclaimer</Text>
            <Text style={styles.body}>
              The App uses third-party artificial intelligence services (including Anthropic's Claude API) to analyze contract text. AI-generated content may contain errors, inaccuracies, or omissions. The App makes no guarantees regarding the accuracy, completeness, or reliability of any analysis.
            </Text>
            <Text style={styles.body}>
              The App may fail to identify important legal issues, misinterpret contract language, or provide suggestions that are not appropriate for your specific situation, jurisdiction, or industry. Always verify any AI-generated analysis with a qualified professional.
            </Text>

            <Text style={styles.sectionTitle}>4. Your API Key</Text>
            <Text style={styles.body}>
              The App requires you to provide your own Claude API key from Anthropic. You are responsible for maintaining the security of your API key and for any charges incurred through its use. The App stores your API key locally on your device only.
            </Text>

            <Text style={styles.sectionTitle}>5. Limitation of Liability</Text>
            <Text style={styles.body}>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, CONTRACTSHIELD AND ITS DEVELOPERS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES ARISING FROM YOUR USE OF THE APP OR RELIANCE ON ANY ANALYSIS PROVIDED BY THE APP.
            </Text>
            <Text style={styles.body}>
              This includes, without limitation, damages arising from: signing a contract based on the App's analysis, failing to identify unfavorable terms, any financial loss resulting from contract decisions, or any inaccuracy in the AI-generated content.
            </Text>

            <Text style={styles.sectionTitle}>6. Indemnification</Text>
            <Text style={styles.body}>
              You agree to indemnify and hold harmless ContractShield, its developers, officers, and agents from any claims, damages, losses, or expenses arising from your use of the App or your reliance on any analysis provided by the App.
            </Text>

            <Text style={styles.sectionTitle}>7. No Warranty</Text>
            <Text style={styles.body}>
              THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </Text>

            <Text style={styles.sectionTitle}>8. Subscription & Payments</Text>
            <Text style={styles.body}>
              Free tier users receive a limited number of contract reviews per month. Pro subscribers receive unlimited reviews for a monthly fee. Subscription terms, pricing, and features are subject to change. You may cancel your subscription at any time.
            </Text>

            <Text style={styles.sectionTitle}>9. Modifications</Text>
            <Text style={styles.body}>
              We reserve the right to modify these Terms at any time. Continued use of the App after changes constitutes acceptance of the modified Terms. Material changes will be communicated through the App.
            </Text>

            <Text style={styles.sectionTitle}>10. Governing Law</Text>
            <Text style={styles.body}>
              These Terms shall be governed by the laws of the State of Oregon, United States, without regard to conflict of law provisions.
            </Text>

            <Text style={styles.sectionTitle}>11. Contact</Text>
            <Text style={styles.body}>
              For questions about these Terms, contact us at: support@contractshield.app
            </Text>
          </>
        )}

        {tab === 'privacy' && (
          <>
            <Text style={styles.updated}>Last updated: {LAST_UPDATED}</Text>

            <Text style={styles.sectionTitle}>1. Overview</Text>
            <Text style={styles.body}>
              ContractShield ("the App") respects your privacy. This Privacy Policy explains what data we collect, how we use it, and your rights regarding your information.
            </Text>

            <Text style={styles.sectionTitle}>2. Data We Collect</Text>

            <Text style={styles.subTitle}>Data Stored Locally on Your Device:</Text>
            <Text style={styles.body}>
              {'\u2022'} Your Claude API key (encrypted in local storage){'\n'}
              {'\u2022'} Contract text you submit for analysis{'\n'}
              {'\u2022'} Analysis results and history{'\n'}
              {'\u2022'} Profile information (name, email) if you choose to provide it{'\n'}
              {'\u2022'} App preferences and settings
            </Text>

            <Text style={styles.subTitle}>Data Sent to Third Parties:</Text>
            <Text style={styles.body}>
              When you submit a contract for analysis, the contract text is sent directly from your device to Anthropic's Claude API servers for processing. This data is transmitted using your personal API key. We do not intercept, store, or have access to this data in transit.
            </Text>

            <Text style={styles.sectionTitle}>3. Data We Do NOT Collect</Text>
            <View style={styles.importantBox}>
              <Text style={styles.importantText}>
                We do NOT operate any servers that receive, store, or process your contract data. All contract analysis happens directly between your device and Anthropic's API. We never see your contracts.
              </Text>
            </View>
            <Text style={styles.body}>
              {'\u2022'} We do not collect analytics or telemetry data{'\n'}
              {'\u2022'} We do not use advertising trackers{'\n'}
              {'\u2022'} We do not sell or share your data with any third parties{'\n'}
              {'\u2022'} We do not have access to your Claude API key
            </Text>

            <Text style={styles.sectionTitle}>4. Third-Party Services</Text>
            <Text style={styles.body}>
              The App uses Anthropic's Claude API for contract analysis. When you submit a contract, the text is sent to Anthropic's servers according to their privacy policy and terms of service. We recommend reviewing Anthropic's privacy policy at anthropic.com/privacy.
            </Text>

            <Text style={styles.sectionTitle}>5. Data Security</Text>
            <Text style={styles.body}>
              All data is stored locally on your device using encrypted storage provided by your operating system. Your API key and contract data never pass through our servers. However, no method of electronic storage is 100% secure, and we cannot guarantee absolute security.
            </Text>

            <Text style={styles.sectionTitle}>6. Data Retention & Deletion</Text>
            <Text style={styles.body}>
              All data is stored on your device. You can delete all app data at any time by clearing the app's storage or uninstalling the App. We retain no copies of your data on any server.
            </Text>

            <Text style={styles.sectionTitle}>7. Children's Privacy</Text>
            <Text style={styles.body}>
              The App is not intended for use by children under the age of 18. We do not knowingly collect information from children.
            </Text>

            <Text style={styles.sectionTitle}>8. Your Rights</Text>
            <Text style={styles.body}>
              Because all data is stored locally on your device, you have full control over your data at all times. You can view, modify, or delete any data through the App's settings or by clearing app storage.
            </Text>

            <Text style={styles.sectionTitle}>9. Changes to This Policy</Text>
            <Text style={styles.body}>
              We may update this Privacy Policy from time to time. Changes will be communicated through the App. Continued use after changes constitutes acceptance.
            </Text>

            <Text style={styles.sectionTitle}>10. Contact</Text>
            <Text style={styles.body}>
              For privacy questions, contact us at: privacy@contractshield.app
            </Text>
          </>
        )}

        <View style={{ height: SPACING.xxxl * 2 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },
  container: { flex: 1 },
  content: { paddingHorizontal: SPACING.lg },

  header: {
    flexDirection: 'row', alignItems: 'center', paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md, backgroundColor: COLORS.surface,
    borderBottomWidth: 1, borderBottomColor: COLORS.border,
  },
  backBtn: { fontSize: 16, color: COLORS.accent, ...FONTS.semibold, marginRight: SPACING.md },
  headerTitle: { fontSize: 18, ...FONTS.bold, color: COLORS.textPrimary },

  tabRow: {
    flexDirection: 'row', paddingHorizontal: SPACING.lg, paddingVertical: SPACING.md,
    backgroundColor: COLORS.surface, borderBottomWidth: 1, borderBottomColor: COLORS.border,
  },
  tabBtn: {
    flex: 1, paddingVertical: SPACING.sm, alignItems: 'center',
    borderRadius: RADIUS.md, marginHorizontal: SPACING.xs,
    backgroundColor: COLORS.surfaceAlt,
  },
  tabBtnActive: { backgroundColor: COLORS.primary },
  tabBtnText: { fontSize: 14, ...FONTS.semibold, color: COLORS.textSecondary },
  tabBtnTextActive: { color: COLORS.textInverse },

  updated: {
    fontSize: 12, color: COLORS.textTertiary, marginTop: SPACING.lg, marginBottom: SPACING.lg,
    textAlign: 'center',
  },

  sectionTitle: {
    fontSize: 16, ...FONTS.bold, color: COLORS.primary,
    marginTop: SPACING.xl, marginBottom: SPACING.sm,
  },
  subTitle: {
    fontSize: 14, ...FONTS.semibold, color: COLORS.textPrimary,
    marginTop: SPACING.md, marginBottom: SPACING.xs,
  },
  body: {
    fontSize: 14, color: COLORS.textPrimary, lineHeight: 22, marginBottom: SPACING.md,
  },

  importantBox: {
    backgroundColor: '#FFF8E7', borderRadius: RADIUS.md, padding: SPACING.lg,
    borderWidth: 1, borderColor: '#F0D060', marginBottom: SPACING.md,
  },
  importantText: {
    fontSize: 14, ...FONTS.semibold, color: COLORS.textPrimary, lineHeight: 22,
  },
});
